apiVersion: apps/v1
kind: Deployment
metadata:
  name: drink-blue
  namespace: foo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: drinks-app
      version: blue
  template:
    metadata:
      labels:
        app: drinks-app
        version: blue
    spec:
      containers:
      - name: drinks-app
        image: replace
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drinks-service
  namespace: foo
spec:
  type: LoadBalancer
  selector:
    app: drinks-app
    version: blue
  ports:
  - port: 80
    targetPort: 8080