apiVersion: apps/v1
kind: Deployment
metadata:
  name: drink-green
  namespace: foo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: drinks-app
      version: green
  template:
    metadata:
      labels:
        app: drinks-app
        version: green
    spec:
      containers:
      - name: drinks-app
        image: adamtravis/rollouts:green
        ports:
        - containerPort: 8080