apiVersion: apps/v1
kind: Deployment
metadata:
  name: drink-green
  namespace: foo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: drinks-app
      version: green
  template:
    metadata:
      labels:
        app: drinks-app
        version: green
    spec:
      containers:
      - name: drinks-app
        image: adamtravis/rollouts:green
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: drinks-service-green
  namespace: foo
spec:
  selector:
    app: drinks-app
    version: green   # switch to green during rollout
  ports:
  - port: 80
    targetPort: 8080